[package]
name = "modern-academic-cv"
version = "0.1.0"
compiler = "0.13.1"
entrypoint = "main.typ"
authors = ["Junyuan Lu"]
license = "Apache-2.0"
description = "An academic cv for graduate school application with modern looking."
keywords = ["CV", "Curriculum Vitae", "Resume", "Modern", "Academic", "Academia", "Graduate Scool", "Application"]
categories = ["cv"]
disciplines = []
repository = "https://github.com/JedimasterLu/Academic-CV-Template"


[template]
path = "template"
entrypoint = "template.typ"
thumbnail = "assets/thumbnail.png"